### ISSUE TITLE
RuntimeError: "pow" not implemented for 'Half'

### ISSUE THREAD

**Issue by leyuan-sun** [MIT-SPARK/llm_scene_understanding#4]
label set: nyuClass lm: GPT-J use cooccurrencies: True use test: True
Traceback (most recent call last):
  File "zero_shot_rooms.py", line 302, in <module>
    acc, analysis_df = dynamic_lm_refinements(
  File "zero_shot_rooms.py", line 100, in dynamic_lm_refinements
    lm_model = GPTJForCausalLM.from_pretrained(
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2619, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 740, in __init__
    self.transformer = GPTJModel(config)
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 489, in __init__
    self.h = nn.ModuleList([GPTJBlock(config) for _ in range(config.n_layer)])
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 489, in <listcomp>
    self.h = nn.ModuleList([GPTJBlock(config) for _ in range(config.n_layer)])
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 294, in __init__
    self.attn = GPTJAttention(config)
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 115, in __init__
    self.embed_positions = create_sinusoidal_positions(max_positions, pos_embd_dim)
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 59, in create_sinusoidal_positions
    inv_freq = 1.0 / (10000 ** (torch.arange(0, dim, 2) / dim))
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/torch/tensor.py", line 29, in wrapped
    return f(*args, **kwargs)
  File "/home/sly/anaconda3/envs/llm/lib/python3.8/site-packages/torch/tensor.py", line 555, in __rpow__
    return torch.tensor(other, dtype=dtype, device=self.device) ** self
RuntimeError: "pow" not implemented for 'Half'

When I try zero-shot-room, this error shows, I use pytorch1.8.1,python3.8,cuda10.2.
Any suggestions?

**Comment by leyuan-sun** [comment]
@verityw I have tried different versions of pytorch, still doesn't work, could you give me some guidance?

**Comment by leyuan-sun** [comment]
NVM, I solved
