### ISSUE TITLE
No module named 'scene_graph_learning'

### ISSUE THREAD

**Issue by leyuan-sun** [MIT-SPARK/llm_scene_understanding#5]
~/llm_scene_understanding$ python zero_shot_rooms.py
label set: nyuClass lm: GPT-J use cooccurrencies: True use test: True
Traceback (most recent call last):
  File "zero_shot_rooms.py", line 302, in <module>
    acc, analysis_df = dynamic_lm_refinements(
  File "zero_shot_rooms.py", line 168, in dynamic_lm_refinements
    dataset = Matterport3dDataset(
  File "/home/sly/llm_scene_understanding/load_matterport3d_dataset.py", line 10, in __init__
    input_data = pickle.load(input_file)
ModuleNotFoundError: No module named 'scene_graph_learning'

Where do you import this module?? @verityw

**Comment by leyuan-sun** [comment]
Solved...
